version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '543:5432'
    volumes:
      - evalia_database:/var/lib/postgresql/data
    networks:
      - EVALIA
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  evalia:
    image: evalia
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PGSQL_DATABASE: ${PGSQL_DATABASE}
      PGSQL_USERNAME: ${PGSQL_USERNAME}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"
    networks:
      - EVALIA

volumes:
  evalia_database:

networks:
  EVALIA:
    driver: bridge
