version: '3'
services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - evalia_database:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - EVALIA
    healthcheck:
      test: "test -f /tmp/sqlend"
      interval: 10s
      retries: 10

  evalia:
    image: evalia
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"
    networks:
      - EVALIA

volumes:
  evalia_database:

networks:
  EVALIA:
     driver: bridge