version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - evalia_database:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - EVALIA
    healthcheck:
      test: "pg_isready -U ${PGSQL_USERNAME}"
      interval: 10s
      retries: 10

  evalia:
    image: evalia
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      PGSQL_DATABASE: ${PGSQL_DATABASE}
      PGSQL_USERNAME: ${PGSQL_USERNAME}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"
    networks:
      - EVALIA

volumes:
  evalia_database:

networks:
  EVALIA:
    driver: bridge
